name: Docker Image for Backend

on:
  push:
    tags:        
      - '**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'backend'
          sparse-checkout-cone-mode: false
      # All files should be moved to the project root.
      - name: Move app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv backend/* .
          rm -rf backend
          ls -lah
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: am009
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: am009/latexdiff-web-backend:latest,am009/latexdiff-web-backend:${{ github.ref_name }}
